config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :availabilities

  get 'reformat_time', to: 'application#reformat_time'

  root 'events#index'
end

app/views/shared/_footer.html.erb
<footer class="footer"><a href="https://github.com/GitGud-KU/Skeddit">Github</a></footer>

app/views/shared/_home.html.erb
<div style="padding-top:15px;"></div>
<%= link_to "Home", events_path, class: "btn btn-info"%>

app/views/shared/_navbar.html.erb
<!-- The following navbar is modelled after the Bootstrap navbar examples
available at https://v4-alpha.getbootstrap.com/components/navbar/
(accessed on 2017-09-16) -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- We use the fluid option here to avoid overriding the fixed width of a normal container within the narrow content columns. -->
  <div class="container-fluid">
    <div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsible">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Skeddit", events_path, class: "navbar-brand" %>
    </div>
	<div class="collapse navbar-collapse" id="collapsible">
      <ul class="nav navbar-nav navbar-right">
		<li style="padding-top:5px;padding-right:5px;">
			<div class="btn-group btn-toggle">
        		<%= link_to "12hr", reformat_time_path, class: session[:hour_format] == 24 ? "btn btn-default" : "btn btn-info active" %>
        		<%= link_to "24hr", reformat_time_path, class: session[:hour_format] == 24 ? "btn btn-info active" : "btn btn-default" %>
  			</div>
    	<li>
		  <% if user_signed_in? %>
			  <li class="dropdown">
				<a href="events" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
				  <li><p>Logged in as: <%= current_user.email %></p></li>
				  <li class="divider"></li>
				  <li><%= link_to('Edit registration', edit_user_registration_path) %></li>

				  <li class="divider"></li>
				  <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
				</ul>
		  	</li>
		<% else %>
			<p class="navbar-btn">
            	<%= link_to('Login', new_user_session_path, class: "btn btn-default")  %>
        	</p>
		<% end %>
      </li>
	  <li style="width:10px;"></li>
    </ul>
</div>
</nav>