config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :availabilities

  get 'reformat_time', to: 'application#reformat_time'

  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  # Every event belongs to an 'admin' user, and has many availabilites and 'participants' (users)
  #   through its availabilities.
  # When an event is destroyed, so are all of its related availabilities.
  belongs_to :owner, class_name: :User, foreign_key: :user_id # admin user
  has_many :availabilities, dependent: :destroy
  has_many :participants, through: :availabilities, source: :user

  # Run compact_times_allowed method before saving an event to the database.
  before_save :compact_times_allowed
  before_save :ensure_times_allowed_has_correct_date

  # Ensures data is in an allowable format before adding it to the database
  validate :name_cannot_be_empty, :must_choose_at_least_one_time, :date_cannot_be_in_the_past
  
  # Array of DateTime values iterating through every 30 minutes on today's date starting from midnight.
  POSSIBLE_TIMES_CONST = Array.new(48).map.with_index{|x,index| Date.today.to_datetime + index * (1.0/48)}

  private

  # Delete all nil values from times_allowed array using ruby's compact method.
  # PRE: None
  # POST: Nil values removed from times_allowed
  def compact_times_allowed
    self.times_allowed = self.times_allowed.compact
  end
  
  # Ensures the name field is not empty
  # PRE: name exists
  # POST: If name is blank, add an error to errors hash.
  def name_cannot_be_empty
    if self.name == ""
      self.errors[:base] << "Name cannot be empty"
    end
  end
  
  # Ensures that at least one time is chosen for the event
  # PRE: times_allowed exists
  # POST: If times_allowed is empty, add an error to errors hash.
  def must_choose_at_least_one_time
    if compact_times_allowed.size <= 0
      self.errors[:base] << "Must choose at least one time slot"
    end
  end
  
  # Verifies event date is not before today
  # PRE: date exists
  # POST: If date is earlier than today, add an error to errors hash.
  def date_cannot_be_in_the_past
    if self.date < Date.today
      self.errors[:base] << "Cannot choose a date in the past"
    end
  end

  # When we created the times, we used today to generate the intervals. 
  # This changes the date of the datetime to the event date.
  # PRE: times_allowed exists
  # POST: Set times_allowed to 
  def ensure_times_allowed_has_correct_date
    self.times_allowed = self.times_allowed.map{|time| time.change(:year => self.date.year,
                                              :month => self.date.month,
                                              :day => self.date.day)}
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  before_action :check_format
  before_action :check_possible_times, :only => [:new, :create, :edit, :update]

  # Create an instance var of all of the events for use in the events#index page
  # PRE: None
  # POST: None
  def index
    @events = Event.all.order(:date)
    @admin_events = @events.select{|event| event.owner == current_user}
    @other_events = @events.reject{|event| event.owner == current_user}
  end

  # Create an instance var of the event with the specified id for the events#show page
  # PRE: None
  # POST: None
  def show
    @event = Event.find(params[:id])
    @times_allowed = @event.times_allowed.map(&:to_datetime)
    @participants = @event.participants
  end

  # Create an instance var for a new event for the events#new pages
  # PRE: None
  # POST: An event object is created
  def new
    @event = Event.new
    @event.user_id = current_user.id
    @possible_times = Event::POSSIBLE_TIMES_CONST
  end

  # Define what to do when creating a new event
  # PRE: None
  # POST: A new event is created, or an error message is shown
  def create
    @event = Event.new(event_params)
    if !(Date.valid_date?(event_params['date(1i)'].to_i,event_params['date(2i)'].to_i,event_params['date(3i)'].to_i))
      @event.errors.add(:base,"Invalid date error")
      @possible_times = Event::POSSIBLE_TIMES_CONST
      render :new
    elsif @event.save
      redirect_to(events_path)
    else
      @possible_times = Event::POSSIBLE_TIMES_CONST
      render :new
    end
  end

  # Find event object to update and store possible_times in a var.
  # PRE: None
  # POST: None
  def edit
    @event = Event.find(params[:id])
    @possible_times = (Event::POSSIBLE_TIMES_CONST).map{|time| time.change( :year => @event.date.year,
                                                                            :month => @event.date.month,
                                                                            :day => @event.date.day)}
  end

  # Define what to do when trying to update an event.
  # PRE: The event with the specific id exists
  # POST: Event is updated with new day, times, or name
  def update
    @event = Event.find(params[:id])
    if !(Date.valid_date?(event_params['date(1i)'].to_i,event_params['date(2i)'].to_i,event_params['date(3i)'].to_i))
      @event.errors.add(:base,"Invalid date error")
      @possible_times = Event::POSSIBLE_TIMES_CONST
      render :edit
    elsif @event.update(event_params)
      redirect_to(events_path)
    else
      @possible_times = (Event::POSSIBLE_TIMES_CONST).map{|time| time.change( :year => @event.date.year,
                                                                              :month => @event.date.month,
                                                                              :day => @event.date.day)}
      render :edit
    end
  end

  # Find and destroy an event. Redirect to events#index.
  # PRE: The event with the specific id exists
  # POST: The event is removed
  def destroy
    @event = Event.find(params[:id])
    @event.destroy if @event.owner == current_user
    redirect_to(events_path)
  end

  private

  # Define the permitted params for creating a new event
  # PRE: None
  # POST: None
  def event_params
    params.require(:event).permit(:name,:date,:user_id,:times_allowed => [])
  end

  # Define a variable with the current hour format setting. If none is set, default to 12.
  # PRE: None
  # POST: None
  def check_format
    @hour_format = session[:hour_format] || 12
  end

  # PRE: None
  # POST: None
  def check_possible_times
    @possible_times = Event::POSSIBLE_TIMES_CONST
  end
end

app/helpers/events_helper.rb
module EventsHelper

  # Get a list of the participants available for a specified event at a specified time.
  # PRE: all param objects are valid
  # POST: None
  def available_participants(participants,event,time)
    participants.select{|p| p.is_available_at_event_and_time?(@event,time) }
  end
end

app/views/events/edit.html.erb
<h1> Edit Event </h1>

<% if @event.errors.any? %>
	<div id="error_explanation" class="alert alert-dismissible alert-danger">
	<h3><%= pluralize(@event.errors.count, "error") %> prevented this event from being created:</h3>

		<ul>
		<% @event.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<%end %>
		</ul>
	</div>
<% end %>

<%= simple_form_for @event do |f| %>
  <%= f.input :name %>
  <%= f.input :date, as: :date, start_year: Date.today.year, end_year: Date.today.year + 8 %>

	<label class="control-label string optional" for="times_allowed">Times Allowed</label>
  <div class="panel panel-default">
    <% if @hour_format == 24 %>
      <%= f.collection_check_boxes :times_allowed, @possible_times, :to_datetime, :hour_24,
        {:item_wrapper_class => 'checkbox_container'} %>
    <% else %>
	    <%= f.collection_check_boxes :times_allowed, @possible_times, :to_datetime, :hour_12,
	  	  {:item_wrapper_class => 'checkbox_container'} %>
    <% end %>
  </div>

  <%= f.hidden_field :user_id %>

  <%= f.button :submit %>
<% end %>

app/views/events/index.html.erb
<h2>Your Events</h2>
<%= link_to "Add Event", new_event_path, class: "btn btn-success btn-lg btn-block" %>
<% if !@admin_events.empty? %>
<table class="table table-striped">
	<thead>
		<tr>
			<th width="60%">Event</th>
			<th width="20%">Date</th>
			<th width="20%">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @admin_events.each do |event| %>
		<tr>
			<td><%= event.name %></td>
			<td><%= event.date.strftime("%a, %B %d, %Y") %></td>
			<td><%= link_to "Results", event_path(event), class: "btn btn-primary btn-sm" %>
				<%= link_to "Edit", edit_event_path(event), class: "btn btn-warning btn-sm" %>
				<%= link_to "Destroy", event_path(event), method: :delete, class: "btn btn-danger btn-sm", :confirm => "Delete this event?" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<% elsif current_user == nil%>
<div class="panel panel-default">
	<div class="panel-body text-center">
		Log in to see your events.
	</div>
</div>
<% else %>
<div class="panel panel-default text-center">
	<div class="panel-body">
		Looks like you have no events. Why don't you create one?
	</div>
</div>
<% end %>
<br>
<h2>Others' Events</h2>
<% if @other_events.any? %>
<table class="table table-striped">
	<thead>
		<tr>
			<th width="30%">Event</th>
			<th width="30%">Owner</th>
			<th width="20%">Date</th>
			<th width="20%">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @other_events.each do |event| %>
		<tr>
			<td><%= event.name %></td>
			<td><%= event.owner.email %></td>
			<td><%= event.date.strftime("%a, %B %d, %Y") %></td>
			<% if(current_user == nil  || !event.participants.include?(current_user)) %>
			<td><%= link_to "Join", new_availability_path(:event_id => event.id), class: "btn btn-primary btn-sm" %></td>
		<% else %>
		<td><%= link_to "Edit", edit_availability_path(event.availabilities.find_by(:user_id => current_user.id)), class: "btn btn-warning btn-sm" %>
		<%= link_to "Leave", availability_path(event.availabilities.find_by(:user_id => current_user.id)), method: :delete, class: "btn btn-danger btn-sm", :confirm => "Delete this event?" %></td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>
<% else %>
<div class="panel panel-default">
	<div class="panel-body text-center">
		Looks like there aren't events. Tell your friends to make some.
	</div>
</div>
<% end %>

app/views/events/new.html.erb
<h1> Create New Event </h1>

<% if @event.errors.any? %>
	<div id="error_explanation" class="alert alert-dismissible alert-danger">
	<h3><%= pluralize(@event.errors.count, "error") %> prevented this event from being created:</h3>

		<ul>
		<% @event.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<%end %>
		</ul>
	</div>
<% end %>

<%= simple_form_for @event do |f| %>
  <%= f.input :name %>
  <%= f.input :date, as: :date, start_year: Date.today.year, end_year: Date.today.year + 8 %>

	<label class="control-label string optional" for="times_allowed">Times Allowed</label>
  <div class="panel panel-default">
    <% if @hour_format == 24 %>
      <%= f.collection_check_boxes :times_allowed, @possible_times, :to_datetime, :hour_24,
        {:item_wrapper_class => 'checkbox_container'} %>
    <% else %>
	    <%= f.collection_check_boxes :times_allowed, @possible_times, :to_datetime, :hour_12,
	  	  {:item_wrapper_class => 'checkbox_container'} %>
    <% end %>
  </div>

  <%= f.hidden_field :user_id %>

  <%= f.button :submit %>
<% end %>

app/views/events/show.html.erb
<div class="container">
	<h1>
		<%= @event.name %>
	</h1>

	<p>
		<b>Date:</b>
		<%= @event.date.strftime("%a, %B %d, %Y") %>
		<br>
		<b>Owner:</b>
		<%= @event.owner.email %>
	</p>
	<br>
	<h3>Availabilities</h3>
	<table class="table table-striped">
		<thead>
			<th style="width:10%;">Times</th>
			<th style="width:20%;">Count</th>
			<th style="width:35%;">Available</th>
			<th style="width:35%;">Unavailable</th>
		</thead>
		<tbody>
			<% @times_allowed.each do |time| %>
			<% available_participants = available_participants(@participants,@event,time)
			unavailable_participants = @event.participants - available_participants%>
				<tr>
					<td><%= @hour_format == 24 ? time.hour_24 : time.hour_12 %></td>
					<td>
						<%= (available_participants.size + 1).to_s + " Availabile" %>
					</td>
					<td>
						<%= available_participants.map{|x| x.email}.append(@event.owner.email).join(", ") %>
					</td>
					<td>
						<%= unavailable_participants.map{|x| x.email}.join(", ") %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>